#######################################################    
# Topic:	Introduction to Makefile - Example 01
# Goal:		Learning Makefile Target 
# Authors:
#   - Redwan (redwan@primesiliconbd.com)
#   - Fattah (fattah@primesiliconbd.com)
#   Modified:	May 1, 2021
#   	Fattah:	Added Header, Footer and Description
#######################################################



default: 
	echo "(Info) This is a test string"

# "default:" is the tag line here (like a switch-case) under which the echo command will be executed





#######################################################
# (Note):	Type "gf" <go file> bringing the cursor
# 		on the absolute link to get into that file
# (Note):	Type "bf" <back file> in command-line mode 
# 		(starting with a colon :) [i.e. ":bf"] to 
# 		get back in the main file
# Test:
# 	Command Line:	make ; give command "make" from shell
# 	Test File: 	/c/Users/fatta/test_git/first_try/makedir/makefile_quickstart_fba/Example_01/test_01.sh	
# Output :
#	Shell Window:
#		Observe the echo'ed commands that executed from source file
#		Observe the output of executed command. [Only echo'ed line for this case]
#		Check if any error message is there and note that down
#	Observe:
#		/c/Users/fatta/test_git/first_try/makedir/makefile_quickstart_fba/Example_01/observe.txt
#			
######################################################
