default: write
	grep -n "the" out_file.txt > match.txt

cleanup:
	rm *.txt

write: 
	echo "(Info) Twinkle, twinkle, little star" > out_file.txt
	echo "(Info) How I wonder what you are " >> out_file.txt
	echo "(Info) Up above the world so high" >> out_file.txt
	echo "(Info) Like a diamond in the sky"  >> out_file.txt
	echo "(Info) Twinkle, twinkle little star" >> out_file.txt
	echo "(Info) How I wonder what you are" >> out_file.txt
